export const ROMANIA_DATA: Record<string, string[]> = {
  "Alba": ["Alba Iulia", "Abrud", "Aiud", "Baia de Arieș", "Blaj", "Câmpeni", "Cugir", "Ocna Mureș", "Sebeș", "Teiuș", "Zlatna", "Albac", "Almașu Mare", "Arieșeni", "Avram Iancu", "Berghin", "Bistra", "Blandiana", "Bucium", "Câlnic", "Cenade", "Cergău", "Ceru-Băcăinți", "Cetatea de Baltă", "Ciugud", "Ciuruleasa", "Crăciunelu de Jos", "Cricău", "Cut", "Daia Română", "Doștat", "Fărău", "Galda de Jos", "Gârbova", "Gârda de Sus", "Hopârta", "Horea", "Ighiu", "Întregalde", "Jidvei", "Livezile", "Lopadea Nouă", "Lunca Mureșului", "Lupsa", "Meteș", "Mihalț", "Mirăslău", "Mogoș", "Noșlac", "Ocoliș", "Ohaba", "Pianu", "Poiana Vadului", "Ponor", "Poșaga", "Rădești", "Râmeț", "Rimetea", "Roșia de Secaș", "Roșia Montană", "Sălciua", "Săliștea", "Săsciori", "Scărișoara", "Sâncel", "Sântimbru", "Sohodol", "Stremț", "Șibot", "Șona", "Șpring", "Șugag", "Unirea", "Vadu Moților", "Valea Lungă", "Vidra", "Vințu de Jos"],
  "Arad": ["Arad", "Chișineu-Criș", "Curtici", "Ineu", "Lipova", "Nădlac", "Pâncota", "Pecica", "Sântana", "Sebiș", "Almaș", "Apateu", "Archiș", "Bârsa", "Bârzava", "Bata", "Beliu", "Birchiș", "Bocsig", "Brazii", "Buteni", "Cărand", "Cermei", "Chisindia", "Conop", "Covăsânț", "Craiva", "Dezna", "Dieci", "Dorobanți", "Fântânele", "Felnac", "Frumușeni", "Ghioroc", "Grăniceri", "Gurahonț", "Hălmagiu", "Hălmăgel", "Hasmaș", "Ignești", "Iratoșu", "Livada", "Macea", "Mișca", "Moneasa", "Olari", "Păuliș", "Peregu Mare", "Petriș", "Pilune", "Pleşcuţa", "Săvârșin", "Secusigiu", "Seleuș", "Semlac", "Sintea Mare", "Socodor", "Șagu", "Șeitin", "Șepreuș", "Șicula", "Șilindia", "Șimand", "Șiria", "Șiștarovăț", "Șofronea", "Tauț", "Târnova", "Ususău", "Vărădia de Mureș", "Vârfurile", "Vinga", "Vladimirescu", "Zăbrani", "Zădăreni", "Zărand", "Zerind", "Zimandu Nou"],
  "Argeș": ["Pitești", "Câmpulung", "Costești", "Curtea de Argeș", "Mioveni", "Ștefănești", "Topoloveni", "Albeștii de Argeș", "Albeștii de Muscel", "Albota", "Aninoasa", "Arefu", "Bascov", "Băbana", "Băiculești", "Bălilești", "Bârla", "Beleți-Negrești", "Berevoesti", "Bogati", "Boteni", "Boțești", "Bradu", "Brăduleț", "Budeasa", "Bughea de Jos", "Bughea de Sus", "Buzoești", "Căldăraru", "Călinești", "Căteasca", "Cepari", "Cetățeni", "Cicănești", "Ciobănești", "Ciomăgești", "Cocu", "Corbeni", "Corbi", "Coșești", "Cotmeana", "Cuca", "Davidești", "Dâmbovicioara", "Dârmănești", "Dobrești", "Domnești", "Drăganu", "Dragoslavele", "Godeni", "Hârsești", "Hârtiești", "Izvoru", "Leordeni", "Lerești", "Lunca Corbului", "Mălureni", "Mărăcineni", "Merișani", "Micești", "Mihăești", "Mioarele", "Miroși", "Morărești", "Moșoaia", "Mozăceni", "Mușătești", "Negrași", "Nucșoara", "Oarja", "Pietroșani", "Poiana Lacului", "Poienarii de Argeș", "Poienarii de Muscel", "Popești", "Priboieni", "Rătești", "Râca", "Recea", "Rociu", "Rucăr", "Sălătrucu", "Săpata", "Schitu Golești", "Slobozia", "Stâlpeni", "Stoenești", "Stolnici", "Suseni", "Ștefan cel Mare", "Șuici", "Teiu", "Tigveni", "Țițești", "Uda", "Ungheni", "Valea Danului", "Valea Iașului", "Valea Mare-Pravăț", "Vedea", "Vlădești", "Vulturești"],
  "Bacău": ["Bacău", "Buhuși", "Comănești", "Dărmănești", "Moinești", "Onești", "Slănic-Moldova", "Târgu Ocna", "Agăș", "Ardeoani", "Asău", "Balcani", "Berești-Bistrița", "Berești-Tazlău", "Berzunți", "Bârsănești", "Blăgești", "Bogdănești", "Brusturoasa", "Buciumi", "Buhoci", "Cașin", "Căiuți", "Cleja", "Colonești", "Corbasca", "Coțofănești", "Dămienești", "Dealu Morii", "Dofteana", "Faraoani", "Filipeni", "Filipești", "Găiceana", "Gârleni", "Ghimeș-Făget", "Gioseni", "Glăvănești", "Gura Văii", "Helegiu", "Hemeiuș", "Huruiești", "Horgești", "Izvoru Berheciului", "Letea Veche", "Lipova", "Livezi", "Luizi-Călugăra", "Măgirești", "Măgura", "Mănăstirea Cașin", "Mărgineni", "Motoșeni", "Negri", "Nicolae Bălcescu", "Odobești", "Oituz", "Oncești", "Orbeni", "Palanca", "Parava", "Pâncești", "Parincea", "Pârgărești", "Pârjol", "Plopana", "Podu Turcului", "Poduri", "Prăjești", "Racova", "Răcăciuni", "Răchitoasa", "Roșiori", "Sănduleni", "Sărata", "Sascut", "Săucești", "Scorțeni", "Secuieni", "Solonț", "Stănișești", "Strugari", "Ștefan cel Mare", "Tamași", "Tătărăști", "Târgu Trotuș", "Traian", "Ungureni", "Urechești", "Valea Seacă", "Vultureni", "Zemeș"],
  "Bihor": ["Oradea", "Aleșd", "Beiuș", "Marghita", "Nucet", "Săcueni", "Salonta", "Ștei", "Valea lui Mihai", "Vașcău", "Abram", "Abrămuț", "Aștileu", "Aușeu", "Avram Iancu", "Balc", "Batăr", "Biharia", "Boianu Mare", "Borod", "Borș", "Bratca", "Brusturi", "Budureasa", "Buduslău", "Bulz", "Buntești", "Căbești", "Câmpani", "Căpâlna", "Cărpinet", "Cefa", "Ceica", "Cetariu", "Cherechiu", "Chișlaz", "Ciuhoi", "Ciumeghiu", "Cociuba Mare", "Copăcel", "Cristioru de Jos", "Curățele", "Curtuișeni", "Derna", "Diosig", "Dobrești", "Drăgănești", "Drăgești", "Finiș", "Gepiu", "Girișu de Criș", "Hidișelu de Sus", "Holod", "Husasău de Tinca", "Ineu", "Lazuri de Beiuș", "Lăzăreni", "Lugașu de Jos", "Luncoiu de Jos", "Mădăras", "Măgești", "Nojorid", "Olcea", "Oșorhei", "Paleu", "Pietroasa", "Pocola", "Pomezeu", "Popești", "Răbăgani", "Remetea", "Rieni", "Roșia", "Roșiori", "Săcădat", "Sălacea", "Sălard", "Sâmbăta", "Sânmartin", "Sânnicolau Român", "Sântandrei", "Sârbi", "Spinuș", "Suplacu de Barcău", "Șimian", "Șinteu", "Șoimi", "Șuncuiuș", "Tarcea", "Tămășeu", "Tăuteu", "Tileagd", "Tinca", "Toboliu", "Tulca", "Țețchea", "Uileacu de Beiuș", "Vadu Crișului", "Vârciorog", "Viișoara"],
  "Bistrița-Năsăud": ["Bistrița", "Beclean", "Năsăud", "Sângeorz-Băi", "Bistrița Bârgăului", "Braniștea", "Budacu de Jos", "Budești", "Căianu Mic", "Cetate", "Chiochiș", "Chiuza", "Ciceu-Giurgești", "Ciceu-Mihăiești", "Coșbuc", "Dumitra", "Dumitrița", "Feldru", "Galații Bistriței", "Ilva Mare", "Ilva Mică", "Josenii Bârgăului", "Lechința", "Leșu", "Livezile", "Lunca Ilvei", "Maieru", "Matei", "Măgura Ilvei", "Mărișelu", "Micestii de Campie", "Milaș", "Monor", "Negrilești", "Nimigea", "Nușeni", "Parva", "Petru Rareș", "Poiana Ilvei", "Prundu Bârgăului", "Rebra", "Rebrișoara", "Rodna", "Romuli", "Runcu Salvei", "Salva", "Sânmihaiu de Câmpie", "Șanț", "Șieu", "Șieu-Măgerviș", "Șieu-Odorhei", "Șieuț", "Șintereag", "Târlișua", "Teaca", "Telciu", "Tiha Bârgăului", "Uriu", "Urmeniș", "Zagra"],
  "Botoșani": ["Botoșani", "Bucecea", "Darabani", "Dorohoi", "Flămânzi", "Săveni", "Ștefănești", "Adășeni", "Albești", "Avrămeni", "Bălușeni", "Blândești", "Brăești", "Broscăuți", "Călărași", "Cândești", "Concesti", "Copălău", "Cordăreni", "Corlăteni", "Corni", "Coșula", "Coțușca", "Cristești", "Cristinești", "Curtești", "Dângeni", "Dersca", "Dimăcheni", "Dobârceni", "Drăgușeni", "Durnești", "Frumușica", "George Enescu", "Gorbănești", "Hănești", "Havârna", "Hilișeu-Horia", "Hlipiceni", "Hudești", "Ibănești", "Leorda", "Lozna", "Lunca", "Manoleasa", "Mihai Eminescu", "Mihăileni", "Mihălășeni", "Mileanca", "Mitoc", "Nicșeni", "Păltiniș", "Pomârla", "Prăjeni", "Răchiți", "Rădăuți-Prut", "Răuseni", "Ripiceni", "Roma", "Românești", "Santa Mare", "Stăuceni", "Suharău", "Sulița", "Șendriceni", "Știubieni", "Todireni", "Trușești", "Tudora", "Ungureni", "Unțeni", "Văculești", "Vârfu Câmpului", "Viișoara", "Vlădeni", "Vlăsinești", "Vorniceni", "Vorona"],
  "Brăila": ["Brăila", "Făurei", "Ianca", "Însurăței", "Bărăganul", "Berteștii de Jos", "Bordei Verde", "Cazașu", "Chiscani", "Ciocile", "Cireșu", "Dudești", "Frecăței", "Galbenu", "Gemenele", "Gropeni", "Jirlău", "Mărașu", "Măxineni", "Mircea Vodă", "Movila Miresii", "Racoviță", "Râmnicelu", "Romanu", "Roșiori", "Salcia Tudor", "Scorțaru Nou", "Siliștea", "Stăncuța", "Surdila-Găiseanca", "Surdila-Greci", "Șuțești", "Tichilești", "Traian", "Tudor Vladimirescu", "Tufești", "Ulmu", "Unirea", "Vădeni", "Victoria", "Vișani", "Viziru", "Zăvoaia"],
  "Brașov": ["Brașov", "Codlea", "Făgăraș", "Ghimbav", "Predeal", "Râșnov", "Rupea", "Săcele", "Victoria", "Zărnești", "Apața", "Augustin", "Beclean", "Bod", "Bran", "Budila", "Bunești", "Cața", "Cincu", "Comăna", "Cristian", "Crizbav", "Drăguș", "Dumbrăvița", "Feldioara", "Fundata", "Hălchiu", "Hărman", "Hârseni", "Hoghiz", "Holbav", "Homorod", "Jibert", "Lisa", "Măieruș", "Mândra", "Moieciu", "Ormeniș", "Părău", "Poiana Mărului", "Prejmer", "Racoș", "Recea", "Sâmbăta de Sus", "Sânpetru", "Șercaia", "Șinca", "Șinca Nouă", "Șoarș", "Tărlungeni", "Teliu", "Ticușu", "Ucea", "Ungra", "Vama Buzăului", "Viștea", "Voila", "Vulcan"],
  "București": ["București", "Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6"],
  "Buzău": ["Buzău", "Nehoiu", "Pătârlagele", "Pogoanele", "Râmnicu Sărat", "Amaru", "Bălăceanu", "Balta Albă", "Beceni", "Berca", "Bisoca", "Blăjani", "Boldu", "Bozioru", "Brădeanu", "Brăești", "Breaza", "Buda", "C.A. Rosetti", "Calvini", "Cănești", "Cătina", "Cernătești", "Chiliile", "Chiojdu", "Cilibia", "Cislău", "Cochirleanca", "Colți", "Costești", "Cozieni", "Florica", "Gălbinași", "Gherăseni", "Ghergheasa", "Glodeanu Sărat", "Glodeanu-Siliștea", "Grebănu", "Gura Teghii", "Largu", "Lopătari", "Luciu", "Măgura", "Mărăcineni", "Mărgăritești", "Mânzălești", "Merei", "Mihăilești", "Movila Banului", "Murgești", "Năeni", "Odăile", "Padina", "Pardoși", "Pănătău", "Pârscov", "Pietroasele", "Podgoria", "Poșta Câlnău", "Racovițeni", "Râmnicelu", "Robeasca", "Rușețu", "Săgeata", "Săhăteni", "Săpoca", "Sărulești", "Scorțoasa", "Scutelnici", "Siriu", "Smeeni", "Stâlpu", "Tisău", "Topliceni", "Țintești", "Ulmeni", "Unguriu", "Vadu Pașii", "Valea Râmnicului", "Valea Salciei", "Vernești", "Vintilă Vodă", "Viperești", "Zărnești", "Ziduri"],
  "Călărași": ["Călărași", "Budești", "Fundulea", "Lehliu Gară", "Oltenița", "Alexandru Odobescu", "Belciugatele", "Borcea", "Chiselet", "Ciocănești", "Crivăț", "Curcani", "Cuza Vodă", "Dichiseni", "Dor Mărunt", "Dorobanțu", "Dragalina", "Dragoș Vodă", "Frăsinet", "Frumușani", "Fundeni", "Gălbinași", "Grădiștea", "Gurbănești", "Ileana", "Independența", "Jegălia", "Lehliu", "Luica", "Luptători", "Mânăstirea", "Mitreni", "Modelu", "Nana", "Nicolae Bălcescu", "Perișoru", "Plătărești", "Radovanu", "Roseți", "Sărulești", "Sohatu", "Spanțov", "Șoldanu", "Ștefan cel Mare", "Ștefan Vodă", "Tămădău Mare", "Ulmeni", "Ulmu", "Unirea", "Vâlcelele", "Valea Argovei", "Vasilați", "Vlad Țepeș"],
  "Caraș-Severin": ["Reșița", "Anina", "Băile Herculane", "Bocșa", "Caransebeș", "Moldova Nouă", "Oravița", "Oțelu Roșu", "Armeniș", "Bănia", "Băuțar", "Berliște", "Berzasca", "Berzovia", "Bolvașnița", "Bozovici", "Brebu", "Brebu Nou", "Buchin", "Bucoșnița", "Carașova", "Cărbunari", "Ciclova Română", "Ciuchici", "Ciudanovița", "Constantin Daicoviciu", "Copăcele", "Cornea", "Cornereva", "Coronini", "Dalboșeț", "Doclin", "Dognecea", "Domașnea", "Eftimie Murgu", "Ezeriș", "Fârliug", "Forotic", "Gârnic", "Glimboca", "Goruia", "Grădinari", "Iablanița", "Lăpușnicel", "Lăpușnicu Mare", "Luncavița", "Lupac", "Marga", "Măureni", "Mehadia", "Mehadica", "Naidăș", "Obreja", "Ocna de Fier", "Păltiniș", "Pojejena", "Prigor", "Răcășdia", "Ramna", "Rusca Montană", "Sacu", "Sasca Montană", "Slatina-Timiș", "Sichevița", "Soceni", "Șopotu Nou", "Târnova", "Teregova", "Ticvaniu Mare", "Topleț", "Turnu Ruieni", "Văliug", "Vărădia", "Vermeș", "Vrani", "Zăvoi", "Zorlențu Mare"],
  "Cluj": ["Cluj-Napoca", "Câmpia Turzii", "Dej", "Gherla", "Huedin", "Turda", "Aghireșu", "Aiton", "Aluniș", "Apahida", "Așchileu", "Baciu", "Băișoara", "Beliș", "Bobâlna", "Bonțida", "Borșa", "Buza", "Căianu", "Călărași", "Călățele", "Cămărașu", "Căpușu Mare", "Cășeiu", "Cătina", "Ceanu Mare", "Chinteni", "Chiuiești", "Ciucea", "Ciurila", "Cojocna", "Cornești", "Cuzdrioara", "Dăbâca", "Feleacu", "Fizeșu Gherlii", "Florești", "Frata", "Gârbău", "Geaca", "Gilău", "Iara", "Iclod", "Izvoru Crișului", "Jichișu de Jos", "Jucu", "Luna", "Luna de Sus", "Măguri-Răcătău", "Mănăstireni", "Mărgău", "Mărișel", "Mica", "Mihai Viteazu", "Mintiu Gherlii", "Mociu", "Moldovenești", "Negreni", "Pălatca", "Panticeu", "Petreștii de Jos", "Ploscoș", "Poieni", "Rășca", "Recea-Cristur", "Săcuieu", "Săndulești", "Săvădisla", "Sâncraiu", "Sânmartin", "Sânpaul", "Sic", "Suatu", "Tritenii de Jos", "Tureni", "Țaga", "Unguraș", "Vad", "Valea Ierii", "Viișoara", "Vultureni"],
  "Constanța": ["Constanța", "Băneasa", "Cernavodă", "Eforie", "Hârșova", "Mangalia", "Medgidia", "Murfatlar", "Năvodari", "Negru Vodă", "Ovidiu", "Techirghiol", "23 August", "Adamclisi", "Agigea", "Albești", "Aliman", "Amzacea", "Bărăganu", "Castelu", "Cerchezu", "Chirnogeni", "Ciobanu", "Ciocârlia", "Cobadin", "Cogealac", "Comana", "Corbu", "Costinești", "Crucea", "Cumpăna", "Cuza Vodă", "Deleni", "Dobromir", "Dumbrăveni", "Fântânele", "Gârliciu", "Ghindărești", "Grădina", "Horia", "Independența", "Ion Corvin", "Istria", "Limanu", "Lipnița", "Lumina", "Mereni", "Mihai Viteazu", "Mihail Kogălniceanu", "Mircea Vodă", "Nicolae Bălcescu", "Oltina", "Ostrov", "Pantelimon", "Pecineaga", "Peștera", "Poarta Albă", "Rasova", "Saligny", "Saraiu", "Săcele", "Seimeni", "Siliștea", "Târgușor", "Topalu", "Topraisar", "Tortoman", "Tuzla", "Valu lui Traian", "Vulturu"],
  "Covasna": ["Sfântu Gheorghe", "Baraolt", "Covasna", "Întorsura Buzăului", "Târgu Secuiesc", "Aita Mare", "Arcuș", "Barcani", "Bățani", "Belin", "Bixad", "Bodoc", "Boroșneu Mare", "Bradut", "Brateș", "Bretcu", "Catalina", "Cernat", "Chichiș", "Comandău", "Dalnic", "Dobârlău", "Estelnic", "Ghelinta", "Ghidfalău", "Hăghig", "Ilieni", "Lemnia", "Malnaș", "Mereni", "Micfalău", "Moacșa", "Ojdula", "Ozun", "Poian", "Reci", "Sânzieni", "Sita Buzăului", "Turia", "Valea Crișului", "Valea Mare", "Vâlcele", "Vârghiș", "Zagon", "Zăbala"],
  "Dâmbovița": ["Târgoviște", "Fieni", "Găești", "Moreni", "Pucioasa", "Răcari", "Titu", "Aninoasa", "Băleni", "Bărbulețu", "Bezdead", "Bilciurești", "Brănești", "Braniștea", "Brezoaele", "Buciumeni", "Bucșani", "Butimanu", "Cândești", "Ciocănești", "Cobia", "Cojasca", "Comișani", "Conțești", "Corbii Mari", "Cornățelu", "Cornești", "Costeștii din Vale", "Crângurile", "Crevedia", "Dărmănești", "Dobra", "Doicești", "Dragodana", "Dragomirești", "Finta", "Glodeni", "Gura Foii", "Gura Ocniței", "Gura Sutii", "Hulubești", "Iedera", "I.L. Caragiale", "Lucieni", "Ludești", "Lungulețu", "Malu cu Flori", "Mănești", "Mătăsaru", "Mogoșani", "Moroeni", "Morteni", "Moțăieni", "Niculești", "Nucet", "Ocnița", "Odobești", "Perșinari", "Petrești", "Pietrari", "Pietroșița", "Poiana", "Potlogi", "Produlești", "Pucheni", "Raciu", "Răscăeți", "Râu Alb", "Răzvad", "Runcu", "Sălcioara", "Slobozia Moară", "Șelaru", "Șotânga", "Tărtășești", "Tătărani", "Uliești", "Ulmi", "Văcărești", "Valea Lungă", "Valea Mare", "Văleni-Dâmbovița", "Vârfuri", "Vișina", "Vișinești", "Voinești", "Vulcana-Băi", "Vulcana-Pandele"],
  "Dolj": ["Craiova", "Băilești", "Bechet", "Calafat", "Dăbuleni", "Filiași", "Segarcea", "Afumați", "Almăj", "Amărăștii de Jos", "Amărăștii de Sus", "Apele Vii", "Argetoaia", "Bârca", "Bistreț", "Botoșești-Paia", "Brabova", "Braloștița", "Bratovoești", "Breasta", "Bucovăț", "Bulzești", "Călărași", "Calopăr", "Caraula", "Cârcea", "Cârna", "Carpen", "Castranova", "Catane", "Celaru", "Cerăt", "Cernătești", "Cetate", "Cioroiași", "Ciupercenii Noi", "Coșoveni", "Coțofenii din Dos", "Coțofenii din Față", "Daneți", "Desa", "Dioști", "Dobrești", "Dobrotești", "Drăgotești", "Drănic", "Fărcaș", "Galicea Mare", "Galiciuica", "Gângiova", "Ghercești", "Ghidici", "Ghindeni", "Gighera", "Giubega", "Giurgița", "Gogoșu", "Goicea", "Goiești", "Grecești", "Intorsura", "Isalnița", "Izvoare", "Leu", "Lipovu", "Măceșu de Jos", "Măceșu de Sus", "Maglavit", "Malu Mare", "Mârșani", "Melinești", "Mischii", "Moțăței", "Murgași", "Negoi", "Orodel", "Ostroveni", "Perișor", "Pielești", "Piscu Vechi", "Plenița", "Pleșoi", "Podari", "Poiana Mare", "Predești", "Radovan", "Rast", "Robănești", "Rojiște", "Sadova", "Sălcuța", "Scaești", "Seaca de Câmp", "Seaca de Pădure", "Secu", "Siliștea Crucii", "Sopot", "Șimnicu de Sus", "Tălpaș", "Teasc", "Terpezița", "Teslui", "Țuglui", "Unirea", "Urzicuța", "Valea Stanciului", "Vârtop", "Vârvoru de Jos", "Vela", "Verbița"],
  "Galați": ["Galați", "Berești", "Târgu Bujor", "Tecuci", "Bălăbănești", "Bălășești", "Băleni", "Băneasa", "Berești-Meria", "Brăhășești", "Buciumeni", "Cavadinești", "Certiești", "Corni", "Corod", "Cosmești", "Costache Negri", "Cuca", "Cudalbi", "Cuza Vodă", "Drăgănești", "Drăgușeni", "Fârțănești", "Foltești", "Frumușița", "Fundeni", "Ghidigeni", "Gohor", "Grivița", "Independența", "Ivești", "Jorăști", "Liești", "Matca", "Măstăcani", "Movileni", "Munteni", "Nămoloasa", "Negrilești", "Nicorești", "Oancea", "Pechea", "Piscu", "Poiana", "Priponești", "Rădești", "Rediu", "Scânteiești", "Schela", "Slobozia Conachi", "Smârdan", "Smulți", "Suceveni", "Suhurlui", "Șendreni", "Tudor Vladimirescu", "Tulucești", "Țepu", "Umbrărești", "Valea Mărului", "Vânători", "Vârlezi", "Vlădești"],
  "Giurgiu": ["Giurgiu", "Bolintin-Vale", "Mihăilești", "Adunații-Copăceni", "Băneasa", "Bolintin-Deal", "Bucșani", "Bulbucata", "Buturugeni", "Călugăreni", "Clejani", "Colibași", "Comana", "Cosoba", "Crevedia Mare", "Daia", "Florești-Stoenești", "Frătești", "Găiseni", "Găujani", "Ghimpați", "Gogoșari", "Gostinari", "Gostinu", "Grădinari", "Greaca", "Herăști", "Hotarele", "Iepurești", "Isvoarele", "Izvoarele", "Joița", "Letca Nouă", "Malu", "Mârșa", "Mihai Bravu", "Ogrezeni", "Oinacu", "Prundu", "Putineiu", "Răsuceni", "Roata de Jos", "Săbăreni", "Schitu", "Singureni", "Slobozia", "Stănești", "Stoenești", "Toporu", "Ulmi", "Valea Dragului", "Vărăști", "Vedea"],
  "Gorj": ["Târgu Jiu", "Bumbești-Jiu", "Motru", "Novaci", "Rovinari", "Târgu Cărbunești", "Țicleni", "Tismana", "Turceni", "Albeni", "Alimpești", "Aninoasa", "Arcani", "Baia de Fier", "Bălănești", "Bălești", "Bărbătești", "Bengești-Ciocadia", "Berlești", "Bâlteni", "Bolboși", "Borăscu", "Brănești", "Bumbești-Pițic", "Bustuchin", "Câlnic", "Căpreni", "Catunele", "Ciuperceni", "Crasna", "Crușet", "Dănciulești", "Dănești", "Drăgotești", "Drăguțești", "Fărcășești", "Glogova", "Godinești", "Hurezani", "Ionești", "Jupânești", "Lelești", "Licurici", "Logrești", "Mătăsari", "Mușetești", "Negomir", "Padeș", "Peștișani", "Plopșoru", "Polovragi", "Prigoria", "Roșia de Amaradia", "Runcu", "Săcelu", "Samarinești", "Săulești", "Schela", "Scoarța", "Slivilești", "Stănești", "Stejari", "Stoina", "Țânțăreni", "Telești", "Turburea", "Turcinești", "Urdari", "Văgiulești", "Vladimir"],
  "Harghita": ["Miercurea Ciuc", "Băile Tușnad", "Bălan", "Borsec", "Cristuru Secuiesc", "Gheorgheni", "Odorheiu Secuiesc", "Toplița", "Vlăhița", "Atid", "Avrămești", "Bilbor", "Brădești", "Căpâlnița", "Cârța", "Ciceu", "Ciucsângeorgiu", "Ciumani", "Corbu", "Corund", "Cozmeni", "Dănești", "Dârjiu", "Dealu", "Ditrău", "Feliceni", "Frumoasa", "Gălăuțaș", "Joseni", "Lăzarea", "Leliceni", "Lueta", "Lunca de Jos", "Lunca de Sus", "Lupeni", "Mădăraș", "Mărtiniș", "Merești", "Mihăileni", "Mugeni", "Ocland", "Păuleni-Ciuc", "Plăieșii de Jos", "Porumbeni", "Praid", "Racu", "Remetea", "Săcel", "Sâncrăieni", "Sândominic", "Sânmartin", "Sânsimion", "Sântimbru", "Sărmaș", "Secuieni", "Siculeni", "Simonești", "Subcetate", "Suseni", "Șimonești", "Tulgheș", "Tușnad", "Ulieș", "Varsag", "Voșlăbeni", "Zetea"],
  "Hunedoara": ["Deva", "Brad", "Călan", "Geoagiu", "Hațeg", "Hunedoara", "Lupeni", "Orăștie", "Petrila", "Petroșani", "Simeria", "Uricani", "Vulcan", "Aninoasa", "Baia de Criș", "Balșa", "Bănița", "Baru", "Băcia", "Băița", "Beriu", "Blăjeni", "Boșorod", "Brănișca", "Bretea Română", "Buceș", "Bucureșci", "Bulzeștii de Sus", "Bunila", "Burjuc", "Cerbăl", "Certeju de Sus", "Cârjiți", "Crișcior", "Densuș", "Dobra", "General Berthelot", "Ghelari", "Gurasada", "Hărău", "Ilia", "Lăpugiu de Jos", "Lelese", "Luncoiu de Jos", "Mărtinești", "Orăștioara de Sus", "Pui", "Rapoltu Mare", "Răchitova", "Ribita", "Râu de Mori", "Romos", "Sarmizegetusa", "Sălașu de Sus", "Sântămăria-Orlea", "Șoimuș", "Teliucu Inferior", "Tomești", "Toplița", "Totești", "Turdaș", "Vața de Jos", "Vălișoara", "Vețel", "Vorța", "Zam"],
  "Ialomița": ["Slobozia", "Amara", "Căzănești", "Fetești", "Fierbinți-Târg", "Tandărei", "Urziceni", "Adâncata", "Albești", "Alexeni", "Andrășești", "Armășești", "Axintele", "Balaciu", "Bărcănești", "Borănești", "Bordușani", "Bucu", "Buești", "Ciocârlia", "Ciochina", "Ciulnița", "Cocora", "Colelia", "Cosâmbești", "Coșereni", "Drăgoești", "Dridu", "Făcăeni", "Gârbovi", "Gheorghe Doja", "Gheorghe Lazăr", "Giurgeni", "Grindu", "Grivița", "Gura Ialomiței", "Ion Roată", "Jilavele", "Maia", "Manasia", "Mărculești", "Mihail Kogălniceanu", "Miloșești", "Moldoveni", "Movila", "Movilița", "Munteni-Buzău", "Ograda", "Perieți", "Platonești", "Reviga", "Roșiori", "Sălcioara", "Sărățeni", "Săveni", "Scânteia", "Sfântu Gheorghe", "Sinești", "Stelnica", "Sudiți", "Traian", "Valea Ciorii", "Valea Măcrișului", "Vlădeni"],
  "Iași": ["Iași", "Hârlău", "Pașcani", "Podu Iloaiei", "Târgu Frumos", "Alexandru I. Cuza", "Andrieșeni", "Aroneanu", "Balș", "Bălțați", "Bârnova", "Belcești", "Bivolari", "Brăești", "Butea", "Ceplenița", "Ciohorăni", "Ciortești", "Ciurea", "Coarnele Caprei", "Comarna", "Costești", "Costuleni", "Cotnari", "Cozmești", "Cristești", "Cucuteni", "Dagâța", "Deleni", "Dobrovăț", "Dolhești", "Drăgușeni", "Dumești", "Erbiceni", "Fântânele", "Focuri", "Golăiești", "Gorban", "Grajduri", "Gropnița", "Grozești", "Hălăucești", "Hărmănești", "Heleșteni", "Holboca", "Horlești", "Ion Neculce", "Ipatele", "Lespezi", "Lețcani", "Lungani", "Mădârjac", "Mircești", "Mironeasa", "Miroslava", "Miroslovești", "Mogoșești", "Mogoșești-Siret", "Moșna", "Moțca", "Movileni", "Oțeleni", "Plugari", "Popești", "Popricani", "Prisăcani", "Probota", "Răchiteni", "Răducăneni", "Redu", "Românești", "Roșcani", "Ruginoasa", "Scânteia", "Schitu Duca", "Scobinți", "Sinești", "Sirețel", "Stolniceni-Prăjescu", "Strunga", "Șcheia", "Șipote", "Tansa", "Tătăruși", "Todirești", "Tomești", "Trifești", "Țibana", "Țibănești", "Țigănași", "Țuțora", "Ungheni", "Valea Lupului", "Valea Seacă", "Victoria", "Vlădeni", "Voinești"],
  "Ilfov": ["Bragadiru", "Buftea", "Chitila", "Măgurele", "Otopeni", "Pantelimon", "Popești-Leordeni", "Voluntari", "1 Decembrie", "Afumați", "Balotești", "Berceni", "Brănești", "Cernica", "Chiajna", "Ciolpani", "Ciorogârla", "Clinceni", "Copăceni", "Corbeanca", "Cornetu", "Dascălu", "Dărăști-Ilfov", "Dobroești", "Domnești", "Dragomirești-Vale", "Găneasa", "Glina", "Grădiștea", "Gruiu", "Jilava", "Moara Vlăsiei", "Mogosoaia", "Nuci", "Periș", "Petrăchioaia", "Snagov", "Ștefăneștii de Jos", "Tunari", "Vidra"],
  "Maramureș": ["Baia Mare", "Baia Sprie", "Borșa", "Cavnic", "Dragomirești", "Săliștea de Sus", "Seini", "Sighetu Marmației", "Șomcuta Mare", "Târgu Lăpuș", "Tăuții-Măgherăuș", "Ulmeni", "Vișeu de Sus", "Ardusat", "Ariniș", "Asuaju de Sus", "Băița de sub Codru", "Băiuț", "Bârsana", "Băsești", "Bicaz", "Bistra", "Bocicoiu Mare", "Bogdan Vodă", "Boiu Mare", "Botiza", "Budești", "Călinești", "Câmpulung la Tisa", "Cernești", "Cicârlău", "Coaș", "Coltău", "Copalnic-Mănăștur", "Coroieni", "Cupșeni", "Desești", "Dumbrăvița", "Fărcașa", "Gârdani", "Giulești", "Groși", "Groșii Țibleșului", "Ieud", "Lăpuș", "Leordina", "Mireșu Mare", "Moisei", "Oarța de Jos", "Ocna Șugatag", "Oncești", "Petrova", "Poienile de sub Munte", "Poienile Izei", "Recea", "Remetea Chioarului", "Remeți", "Repedea", "Rona de Jos", "Rona de Sus", "Rozavlea", "Ruscova", "Săcălășeni", "Săcel", "Sălsig", "Săpânța", "Sarasău", "Satulung", "Sie u", "Sisești", "Strâmtura", "Suciu de Sus", "Șieu", "Șișești", "Vadu Izei", "Valea Chioarului", "Vima Mică", "Vișeu de Jos"],
  "Mehedinți": ["Drobeta-Turnu Severin", "Baia de Aramă", "Orșova", "Strehaia", "Vânju Mare", "Bâcleș", "Bala", "Bălăcița", "Balta", "Bălănești", "Breznița-Motru", "Breznița-Ocol", "Broșteni", "Burila Mare", "Butoiești", "Căzănești", "Cireșu", "Corcova", "Corlățel", "Cujmir", "Dârvari", "Devesel", "Dubova", "Dumbrava", "Eșelnița", "Florești", "Gârla Mare", "Godeanu", "Gogoșu", "Greci", "Grozești", "Gruia", "Hinova", "Husnicioara", "Ilovăț", "Ilovița", "Isverna", "Izvoru Bârzii", "Jiana", "Livezile", "Malovăț", "Obârșia de Câmp", "Obârșia-Cloșani", "Oprișor", "Pădina", "Pătulele", "Podeni", "Ponoarele", "Poroina Mare", "Pristol", "Prunișor", "Punghina", "Rogova", "Salcia", "Stângăceaua", "Svinița", "Șimian", "Șișești", "Șovarna", "Tâmna", "Vânători", "Vânjuleț", "Vlădaia", "Voloiac", "Vrata"],
  "Mureș": ["Târgu Mureș", "Iernut", "Luduș", "Miercurea Nirajului", "Reghin", "Sângeorgiu de Pădure", "Sărmașu", "Sighișoara", "Sovata", "Târnăveni", "Ungheni", "Acățari", "Adămuș", "Albești", "Aluniș", "Apold", "Ațintiș", "Bahnea", "Band", "Batoș", "Băgaciu", "Băla", "Bălăușeri", "Beica de Jos", "Bereni", "Bichiș", "Bogata", "Brâncovenești", "Breaza", "Ceuașu de Câmpie", "Chețani", "Chibed", "Chiheru de Jos", "Coroisânmărtin", "Corunca", "Cozma", "Crăciunești", "Craiova", "Cristești", "Cucerdea", "Cuci", "Daneș", "Deda", "Eremitu", "Ernei", "Fărăgău", "Fântânele", "Gălești", "Gănești", "Gheorghe Doja", "Ghindari", "Glodeni", "Gornești", "Grebenișu de Câmpie", "Gurghiu", "Hodac", "Hodoșa", "Ibănești", "Iclănzel", "Ideciu de Jos", "Livezeni", "Lunca", "Lunca Bradului", "Mădăraș", "Măgherani", "Mica", "Miheșu de Câmpie", "Nadeș", "Neaua", "Ogra", "Papiu Ilarian", "Pănet", "Păsăreni", "Petelea", "Pogăceaua", "Râciu", "Răstolița", "Rușii-Munți", "Sâncraiu de Mureș", "Sângeorgiu de Mureș", "Sânpaul", "Sânpetru de Câmpie", "Sântana de Mureș", "Sărățeni", "Saschiz", "Solovăstru", "Stânceni", "Suplac", "Suseni", "Șăulia", "Șincai", "Tăureni", "Valea Largă", "Vânători", "Vărgata", "Vătava", "Viișoara", "Voivodeni", "Zagăr", "Zau de Câmpie"],
  "Neamț": ["Piatra Neamț", "Bicaz", "Roman", "Roznov", "Târgu Neamț", "Agapia", "Alexandru cel Bun", "Bahna", "Bălțătești", "Bâra", "Bârgăuani", "Bodești", "Boghicea", "Borca", "Borlești", "Botești", "Bozieni", "Brusturi", "Cândești", "Ceahlău", "Cordun", "Costisa", "Crăcăoani", "Dămuc", "Dobreni", "Dochia", "Doljești", "Dragomirești", "Drăgănești", "Dulcești", "Dumbrava Roșie", "Farcașa", "Făurei", "Gârcina", "Gherăești", "Ghindăoani", "Girov", "Grințieș", "Grumăzești", "Hangu", "Horia", "Icușești", "Ion Creangă", "Mărgineni", "Moldoveni", "Negrești", "Oniceni", "Păstrăveni", "Pângărați", "Petricani", "Piatra Șoimului", "Pipirig", "Podoleni", "Poiana Teiului", "Poienari", "Răucești", "Războieni", "Rediu", "Români", "Ruginoasa", "Săbăoani", "Săvinești", "Secuieni", "Stănița", "Ștefan cel Mare", "Tarcău", "Tașca", "Tazlău", "Tămășeni", "Timișești", "Trifești", "Tupilați", "Țibucani", "Urecheni", "Valea Ursului", "Văleni", "Vânători-Neamț", "Zănești"],
  "Olt": ["Slatina", "Balș", "Corabia", "Drăgănești-Olt", "Piatra-Olt", "Potcoava", "Scornicești", "Caracal", "Băbiciu", "Baldovinești", "Bărăști", "Bârza", "Bobicești", "Brastavățu", "Brebeni", "Brâncoveni", "Bucinișu", "Călui", "Cârlogani", "Cezieni", "Cilieni", "Colonești", "Corbu", "Coteana", "Crâmpoia", "Cungrea", "Curtișoara", "Dăneasa", "Deveselu", "Dobrețu", "Dobrosloveni", "Dobroteasa", "Dobrun", "Drăghiceni", "Făgețelu", "Fălcoiu", "Fărcașele", "Găneasa", "Găvănești", "Gârcov", "Giuvărăști", "Gostavățu", "Grădinari", "Grădinile", "Grozăvești", "Gura Padinii", "Iancu Jianu", "Icoana", "Ipotești", "Izbiceni", "Izvoarele", "Leleasca", "Mărunței", "Mihăești", "Milcov", "Morunglav", "Movileni", "Nicolae Titulescu", "Obârșia", "Oboga", "Oporelu", "Optași-Măgura", "Orlea", "Osica de Jos", "Osica de Sus", "Pârșcoveni", "Perieți", "Plesoiu", "Poboru", "Priseaca", "Radomirești", "Redea", "Rotunda", "Rusănești", "Sâmburești", "Sârbii-Măgura", "Schitu", "Seaca", "Slătioara", "Spineni", "Sprâncenata", "Stoenești", "Stoicănești", "Strejești", "Studina", "Șerbănești", "Șopârlița", "Ștefan cel Mare", "Tătulești", "Teslui", "Tia Mare", "Topana", "Traian", "Tufeni", "Urzica", "Vădastra", "Vădăstrița", "Vâlcele", "Valea Mare", "Văleni", "Verguleasa", "Vișina", "Vișina Nouă", "Vitomirești", "Vlădila", "Voineasa", "Vulpeni", "Vulturești"],
  "Prahova": ["Ploiești", "Azuga", "Băicoi", "Boldești-Scăeni", "Breaza", "Bușteni", "Câmpina", "Comarnic", "Mizil", "Plopeni", "Sinaia", "Slănic", "Urlați", "Vălenii de Munte", "Adunați", "Albești-Paleologu", "Aluniș", "Apostolache", "Ariceștii Rahtivani", "Ariceștii Zeletin", "Baba Ana", "Balta Doamnei", "Bălțești", "Bănești", "Bărcănești", "Bătrâni", "Berceni", "Bertea", "Blejoi", "Boldești-Gradiștea", "Brazi", "Brebu", "Bucov", "Călugăreni", "Cărbunești", "Ceptura", "Chiojdeanca", "Ciorani", "Cocorăștii Colț", "Cocorăștii Mislii", "Colceag", "Cornu", "Cosminele", "Drăgănești", "Drajna", "Dumbrava", "Dumbrăvești", "Fântânele", "Filipeștii de Pădure", "Filipeștii de Târg", "Florești", "Fulga", "Gherghița", "Gorgota", "Gornet", "Gornet-Cricov", "Gura Vadului", "Gura Vitioarei", "Iordăcheanu", "Izvoarele", "Jugureni", "Lapoș", "Lipănești", "Măgurele", "Măgureni", "Măneciu", "Mănești", "Olari", "Păcureți", "Păulești", "Plopu", "Podenii Noi", "Poiana Câmpina", "Poienarii Burchii", "Posești", "Predeal-Sărari", "Provița de Jos", "Provița de Sus", "Puchenii Mari", "Râfov", "Salcia", "Sălciile", "Scorțeni", "Secăria", "Sângeru", "Șirna", "Șoimari", "Șotrile", "Ștefești", "Surani", "Talea", "Tătaru", "Teișani", "Telega", "Tinosu", "Târgșoru Vechi", "Tomșani", "Vadu Săpat", "Vâlcănești", "Valea Călugărească", "Valea Doftanei", "Vărbilău"],
  "Satu Mare": ["Satu Mare", "Ardud", "Carei", "Livada", "Negrești-Oaș", "Tășnad", "Acâș", "Agriș", "Andrid", "Apa", "Bătarci", "Beltiug", "Berveni", "Bârsău", "Bixad", "Bogdand", "Botiz", "Călinești-Oaș", "Cămărzana", "Cămin", "Căpleni", "Căuaș", "Cehal", "Certeze", "Craidorolț", "Crucișor", "Culciu", "Doba", "Dorolț", "Foieni", "Gherța Mică", "Halmeu", "Hodod", "Homoroade", "Lazuri", "Medieșu Aurit", "Micula", "Moftin", "Odoreu", "Orașu Nou", "Păulești", "Petrești", "Pișcolt", "Pomi", "Porumbești", "Racșa", "Săcășeni", "Sanislău", "Santău", "Săuca", "Socond", "Supur", "Tarna Mare", "Terebești", "Tiream", "Târșolț", "Turț", "Turulung", "Urziceni", "Valea Vinului", "Vama", "Vetiș", "Viile Satu Mare"],
  "Sălaj": ["Zalău", "Cehu Silvaniei", "Jibou", "Șimleu Silvaniei", "Agrij", "Almașu", "Băbeni", "Bălan", "Bănișor", "Benesat", "Bobota", "Bocșa", "Boghiș", "Buciumi", "Camăr", "Carastelec", "Chieșd", "Cizer", "Coșeiu", "Crasna", "Creaca", "Crișeni", "Cristolț", "Cuzăplac", "Dobrin", "Dragu", "Fildu de Jos", "Gâlgău", "Gârbou", "Halmășd", "Hereclean", "Hida", "Horoatu Crasnei", "Ileanda", "Ip", "Letca", "Lozna", "Măeriște", "Marca", "Meseșenii de Jos", "Mirșid", "Năpradea", "Nușfalău", "Pericei", "Plopiș", "Poiana Blenchii", "Românași", "Rus", "Săg", "Sălățig", "Sâg", "Sânmihaiu Almașului", "Someș-Odorhei", "Surduc", "Șamșud", "Șărmășag", "Șimișna", "Treznea", "Valcău de Jos", "Vârșolț", "Zalha", "Zimbor"],
  "Sibiu": ["Sibiu", "Agnita", "Avrig", "Cisnădie", "Copșa Mică", "Dumbrăveni", "Mediaș", "Miercurea Sibiului", "Ocna Sibiului", "Săliște", "Tălmaciu", "Alma", "Alțina", "Apoldu de Jos", "Arpașu de Jos", "Ațel", "Axente Sever", "Bazna", "Bârghiș", "Biertan", "Blăjel", "Boița", "Brateiu", "Brădeni", "Bruiu", "Chirpăr", "Cârța", "Cârțișoara", "Cristian", "Dârlos", "Gura Râului", "Hoghilag", "Iacobeni", "Jina", "Laslea", "Loamneș", "Ludoș", "Marpod", "Merghindeal", "Micăsasa", "Mihăileni", "Moșna", "Nocrich", "Orlat", "Păuca", "Poiana Sibiului", "Poplaca", "Porumbacu de Jos", "Racovița", "Rășinari", "Râu Sadului", "Roșia", "Sadu", "Slimnic", "Șeica Mare", "Șeica Mică", "Șelimbăr", "Șura Mare", "Șura Mică", "Târnava", "Tilișca", "Turnu Roșu", "Valea Viilor", "Vurpăr"],
  "Suceava": ["Suceava", "Broșteni", "Cajvana", "Câmpulung Moldovenesc", "Dolhasca", "Fălticeni", "Frasin", "Gura Humorului", "Liteni", "Milișăuți", "Rădăuți", "Salcea", "Siret", "Solca", "Vatra Dornei", "Vicovu de Sus", "Adâncata", "Arbore", "Baia", "Bălăceana", "Bălcăuți", "Berchișești", "Bilca", "Bogdănești", "Boroaia", "Bosanci", "Breaza", "Brodina", "Bunești", "Burla", "Cacica", "Calafindești", "Capu Câmpului", "Cârlibaba", "Cornu Luncii", "Coșna", "Crucea", "Dărmănești", "Dolhești", "Dorna-Arini", "Dorna Candrenilor", "Dornești", "Drăgoiești", "Drăgușeni", "Dumbrăveni", "Fântâna Mare", "Fântânele", "Forăști", "Frătăuții Noi", "Frătăuții Vechi", "Frumosu", "Fundu Moldovei", "Gălănești", "Grămești", "Grănicești", "Hănțești", "Hârtop", "Horodnic de Jos", "Horodnic de Sus", "Horodniceni", "Iacobeni", "Iaslovăț", "Ilișești", "Ipotești", "Izvoarele Sucevei", "Marginea", "Mălini", "Mănăstirea Humorului", "Mitocu Dragomirnei", "Moara", "Moldova-Sulița", "Moldovița", "Mușenița", "Ostra", "Păltinoasa", "Panaci", "Pârteștii de Jos", "Pătrăuți", "Poiana Stampei", "Poieni-Solca", "Pojorâta", "Preutești", "Putna", "Rădășeni", "Râșca", "Sadova", "Satu Mare", "Siminicea", "Slatina", "Straja", "Stroiești", "Stulpicani", "Sucevița", "Șaru Dornei", "Șcheia", "Șerbăuți", "Todirești", "Udești", "Ulma", "Vadu Moldovei", "Valea Moldovei", "Vama", "Vatra Moldoviței", "Verești", "Vicovu de Jos", "Voitinel", "Volovăț", "Vulturești", "Zamostea", "Zvoriștea"],
  "Teleorman": ["Alexandria", "Roșiorii de Vede", "Turnu Măgurele", "Videle", "Zimnicea", "Balaci", "Băbăița", "Beuca", "Blejești", "Bogdana", "Botoroaga", "Bragadiru", "Brânceni", "Bujoreni", "Buzescu", "Călinești", "Călmățuiu", "Călmățuiu de Sus", "Cervenia", "Ciolănești", "Ciuperceni", "Conțești", "Cosmești", "Crângu", "Crevenicu", "Crângeni", "Didești", "Dobrotești", "Drăgănești de Vede", "Drăgănești-Vlașca", "Fântânele", "Frăsinet", "Frumoasa", "Furculești", "Gălăteni", "Gratia", "Islaz", "Izvoarele", "Lisa", "Lița", "Lunca", "Măgura", "Măldăeni", "Mârzănești", "Mavrodin", "Mereni", "Moșteni", "Nanov", "Năsturelu", "Necșești", "Nenciulești", "Olteni", "Orbeasca", "Peretu", "Piatra", "Pietroșani", "Plopii-Slăvitești", "Plosca", "Poeni", "Poroschia", "Purani", "Putineiu", "Rădoiești", "Răsmirești", "Saelele", "Salcia", "Săceni", "Scrioaștea", "Scurtu Mare", "Seaca", "Segarcea-Vale", "Sfințești", "Siliștea", "Siliștea Gumești", "Slobozia Mândra", "Smârdioasa", "Stejaru", "Storobăneasa", "Suhaia", "Talpa", "Tătărăștii de Jos", "Tătărăștii de Sus", "Țigănești", "Traian", "Trivalea-Moșteni", "Troianul", "Uda-Clocociov", "Vârtoape", "Vedea", "Viișoara", "Vitănești", "Zâmbreasca"],
  "Timiș": ["Timișoara", "Buziaș", "Ciacova", "Deta", "Făget", "Gătaia", "Jimbolia", "Lugoj", "Recaș", "Sânnicolau Mare", "Balinț", "Banloc", "Bara", "Bârna", "Beba Veche", "Becicherecu Mic", "Belinț", "Bethausen", "Biled", "Birda", "Bogda", "Boldur", "Brestovăț", "Bucovăț", "Cărpiniș", "Cenad", "Cenei", "Checea", "Chevereșu Mare", "Comloșu Mare", "Coșteiu", "Criciova", "Curtea", "Darova", "Denta", "Dudeștii Noi", "Dudeștii Vechi", "Dumbrava", "Dumbrăvița", "Fârdea", "Fibiș", "Foeni", "Gavojdia", "Ghilad", "Ghiroda", "Ghizela", "Giarmata", "Giera", "Giroc", "Giulvăz", "Gottlob", "Iecea Mare", "Jamu Mare", "Jebel", "Lenauheim", "Liebling", "Livezile", "Lovrin", "Margina", "Mașloc", "Mănăștiur", "Moravița", "Moșnița Nouă", "Nădrag", "Nițchidorf", "Ohaba Lungă", "Orțișoara", "Otelec", "Pădureni", "Parța", "Peciu Nou", "Periam", "Pesac", "Pietroasa", "Pișchia", "Racovița", "Remetea Mare", "Săcălaz", "Sacoșu Turcesc", "Sag", "Sânandrei", "Sânmihaiu Român", "Sânpetru Mare", "Saravale", "Satchinez", "Secaș", "Știuca", "Teremia Mare", "Tomești", "Tomnatic", "Topolovățu Mare", "Tormac", "Traian Vuia", "Uivar", "Valcani", "Variaș", "Victor Vlad Delamarina", "Voiteg"],
  "Tulcea": ["Tulcea", "Babadag", "Isaccea", "Măcin", "Sulina", "Baia", "Beidaud", "Beștepe", "C.A. Rosetti", "Carcaliu", "Casimcea", "Ceamurlia de Jos", "Ceatalchioi", "Cerna", "Chilia Veche", "Ciucurova", "Crișan", "Dăeni", "Dorobanțu", "Frecăței", "Greci", "Grindu", "Hamcearca", "Horia", "I.C. Brătianu", "Izvoarele", "Jijila", "Jurilovca", "Luncavița", "Mahmudia", "Maliuc", "Mihai Bravu", "Mihail Kogălniceanu", "Murighiol", "Nalbant", "Niculițel", "Nufăru", "Ostrov", "Pardina", "Peceneaga", "Sarichioi", "Sfântu Gheorghe", "Slava Cercheză", "Smârdan", "Somova", "Stejaru", "Topolog", "Turcoaia", "Văcăreni", "Valea Nucarilor", "Valea Teilor"],
  "Vaslui": ["Vaslui", "Bârlad", "Huși", "Murgeni", "Negrești", "Albești", "Alexandru Vlahuță", "Arsura", "Băcani", "Băcești", "Bălteni", "Berezeni", "Blăgești", "Bogdana", "Bogdănești", "Bogdănița", "Boțești", "Bunești-Averești", "Ciocani", "Codăești", "Coroiești", "Costești", "Cozmești", "Crețești", "Dănești", "Deleni", "Delești", "Dimitrie Cantemir", "Dodești", "Dragomirești", "Drânceni", "Duda-Epureni", "Dumești", "Epureni", "Fălciu", "Ferești", "Fruntișeni", "Găgești", "Gârceni", "Gherghești", "Grivița", "Hoceni", "Iana", "Ibănești", "Ivănești", "Ivești", "Laza", "Lipovăț", "Lunca Banului", "Mălușteni", "Miclești", "Muntenii de Jos", "Muntenii de Sus", "Oltenești", "Oșești", "Pădureni", "Perieni", "Pochidia", "Pogana", "Pogonești", "Poienești", "Puiești", "Pungești", "Pușcași", "Rafaila", "Rebricea", "Roșiești", "Solești", "Stănilești", "Ștefan cel Mare", "Șuletea", "Tăcuta", "Tanacu", "Tătărăni", "Todirești", "Tutova", "Văleni", "Vetrisoaia", "Viișoara", "Vinderei", "Voinești", "Vulturești", "Vutcani", "Zăpodeni", "Zorleni"],
  "Vâlcea": ["Râmnicu Vâlcea", "Băbeni", "Băile Govora", "Băile Olănești", "Bălcești", "Berbești", "Brezoi", "Călimănești", "Drăgășani", "Horezu", "Ocnele Mari", "Alunu", "Amărăști", "Bărbătești", "Berislăvești", "Boișoara", "Budești", "Bujoreni", "Bunești", "Cernișoara", "Copăceni", "Costești", "Crețeni", "Dăești", "Dănicei", "Diculești", "Drăgoești", "Fârtățești", "Faurești", "Frâncești", "Galicea", "Ghioroiu", "Glăvile", "Golești", "Grădiștea", "Gușoeni", "Ionești", "Lăcusteni", "Lădești", "Laloșu", "Livezi", "Lungești", "Măciuca", "Mădulari", "Malaia", "Mateești", "Mihăești", "Milcoiu", "Mitrofani", "Muereasca", "Nicolae Bălcescu", "Olanu", "Orlești", "Oteșani", "Păușești", "Păușești-Măglași", "Perișani", "Pesceana", "Pietrari", "Popești", "Prundeni", "Racovița", "Roești", "Roșiile", "Runcu", "Sălătrucel", "Scundu", "Sinești", "Slătioara", "Stănești", "Stoenești", "Stoilești", "Stroești", "Șirineasa", "Ștefănești", "Sutești", "Tetoiu", "Titești", "Tomșani", "Vaideeni", "Valea Mare", "Vlădești", "Voicești", "Voineasa", "Zătreni"],
  "Vrancea": ["Focșani", "Adjud", "Mărășești", "Odobești", "Panciu", "Andreiașu de Jos", "Bălești", "Bârsești", "Biliești", "Boghești", "Bolotești", "Bordești", "Broșteni", "Câmpineanca", "Câmpuri", "Cârligele", "Chiojdeni", "Ciorăști", "Corbița", "Cotești", "Dumbrăveni", "Dumitrești", "Fitionești", "Garoafa", "Golești", "Gologanu", "Gugești", "Gura Caliței", "Homocea", "Jariștea", "Jitia", "Măicănești", "Mera", "Milcovul", "Movilița", "Nănbești", "Năruja", "Negrilești", "Nereju", "Nistorești", "Obrejița", "Paltin", "Păulești", "Păunești", "Ploscuțeni", "Poiana Cristei", "Popești", "Pufești", "Răcoasa", "Răstoaca", "Reghiu", "Ruginești", "Sihlea", "Slobozia Bradului", "Slobozia Ciorăști", "Soveja", "Spulber", "Străoane", "Suraia", "Tănăsoaia", "Tătăranu", "Țifești", "Tâmboiești", "Tulnici", "Urechești", "Valea Sării", "Vânători", "Vârteșcoiu", "Vidra", "Vintileasca", "Vizantea-Livezi", "Vrâncioaia", "Vulturu"]
};

export const ROMANIA_NEIGHBORHOODS: Record<string, string[]> = {
  // --- BUCUREȘTI & ILFOV ---
  "București": ["Aviației", "Băneasa", "Berceni", "Centrul Civic", "Colentina", "Cotroceni", "Crângași", "Dorobanți", "Dristor", "Drumul Taberei", "Ferentari", "Floreasca", "Ghencea", "Giulești", "Grivița", "Iancului", "Lipscani", "Militari", "Moșilor", "Obor", "Pajura", "Pantelimon", "Pipera", "Primăverii", "Rahova", "Ștefan cel Mare", "Tei", "Tineretului", "Titan", "Unirii", "Văcărești", "Vitan"],
  "Sector 1": ["Aviației", "Băneasa", "Bucureștii Noi", "Dămăroaia", "Domenii", "Dorobanți", "Floreasca", "Gara de Nord", "Grivița", "Pajura", "Pipera", "Primăverii", "Romană", "Victoriei"],
  "Sector 2": ["Andronache", "Baicului", "Colentina", "Fundeni", "Iancului", "Moșilor", "Obor", "Pantelimon", "Ștefan cel Mare", "Tei", "Vatra Luminoasă"],
  "Sector 3": ["Balta Albă", "Centrul Civic", "Dristor", "Dudești", "Lipscani", "Muncii", "Titan", "Unirii", "Vitan", "Vitan-Bârzești"],
  "Sector 4": ["Apărătorii Patriei", "Berceni", "Brâncoveanu", "Giurgiului", "Olteniței", "Tineretului", "Văcărești"],
  "Sector 5": ["13 Septembrie", "Cotroceni", "Ferentari", "Ghencea", "Rahova", "Sălaj"],
  "Sector 6": ["Crângași", "Drumul Taberei", "Giulești", "Militari", "Regie"],

  // --- ALBA ---
  "Alba Iulia": ["Ampoi 1", "Ampoi 2", "Ampoi 3", "Carolina", "Centru", "Cetate", "Lipoveni", "Maieri", "Micești", "Oarda", "Partoș", "Platoul Romanilor", "Tolstoi"],

  // --- ARAD ---
  "Arad": ["Alfa", "Aradul Nou", "Aurel Vlaicu", "Bujac", "Calea 6 Vânători", "Calea Romanilor", "Centru", "Confecții", "Drăgășani", "Funcționarilor", "Gai", "Grădiște", "Micălaca", "Pârneava", "Poltura", "Sânnicolau Mic", "Șega", "Subcetate"],

  // --- ARGEȘ ---
  "Pitești": ["Banat", "Big", "Calea București", "Centru", "Craiovei", "Eremia Grigorescu", "Găvana 1", "Găvana 2", "Găvana 3", "Mărășești", "Nord", "Prundu", "Războieni", "Traian", "Trivale", "Tudor Vladimirescu"],

  // --- BACĂU ---
  "Bacău": ["Alecu Russo", "Bistrița Lac", "C.F.R.", "Centru", "Cornișa 1", "Cornișa 2", "Gherăiești", "Izvoare", "Miorița", "Neagoe Vodă", "Nord", "Orizont", "Republicii", "Șerbănești", "Ștefan cel Mare", "Sud", "Tache", "Ura"],

  // --- BIHOR ---
  "Oradea": ["Cantemir", "Centru Civic", "Decebal - Dacia", "Dragoș Vodă", "Episcopia Bihor", "Europa", "Gheorghe Doja", "Ioșia", "Ioșia Nord", "Nufărul 1", "Nufărul 2", "Olosig", "Oncea", "Podgoria", "Rogerius", "Salca", "Splaiul Crișanei", "Subcetate", "Tokai", "Velenta", "Velența"],

  // --- BISTRIȚA-NĂSĂUD ---
  "Bistrița": ["Centru", "Decebal", "Gării", "Independenței", "Libertății", "Sigmir", "Subcetate", "Ștefan cel Mare", "Unirea", "Viișoara"],

  // --- BOTOȘANI ---
  "Botoșani": ["Bucovina", "Centru Vechi", "Grivița", "Împăratul Traian", "Luizoaia", "Pacea", "Primăverii", "Sucevei", "Teatrului"],

  // --- BRĂILA ---
  "Brăila": ["Ansamblul Buzăului", "Apollo", "Bariera Călărașilor", "Brăilița", "Călărași 4", "Catanga", "Centru", "Chercea", "Comorofca", "Gara", "Hipodrom", "Islaz", "Lacu Dulce", "Obor", "Plantelor", "Progresul", "Radu Negru", "Vidin", "Viziru 1", "Viziru 2", "Viziru 3"],

  // --- BRAȘOV ---
  "Brașov": ["Astra", "Bartolomeu", "Blumăna", "Centrul Civic", "Centrul Vechi", "Craiter", "Florilor", "Gara", "Noua", "Prund-Schei", "Răcădău (Valea Cetății)", "Scriitorilor", "Stupini", "Tractorul", "Triaj"],

  // --- BUZĂU ---
  "Buzău": ["1 Decembrie 1918", "23 August", "Broșteni", "Centru", "Crâng", "Dorobanți 1", "Dorobanți 2", "Gară", "Marghiloman", "Micro 14", "Micro 3", "Micro 5", "Mihai Viteazu", "Nicolae Bălcescu", "Orizont", "Poștei", "Unirii"],

  // --- CARAȘ-SEVERIN ---
  "Reșița": ["Câlnic", "Centru", "Doman", "Lend", "Lunca Bârzavei (Govândari)", "Moroasa", "Muncitoresc", "Stavila", "Valea Domanului"],

  // --- CĂLĂRAȘI ---
  "Călărași": ["10 Nivele", "5 Călărași", "Caramidari", "Centru", "Cerneală", "Farfuria", "Măgureni", "Mircea Vodă", "Orizont"],

  // --- CLUJ ---
  "Cluj-Napoca": ["Andrei Mureșanu", "Becas", "Borhanci", "Bulgaria", "Bună Ziua", "Centru", "Dâmbu Rotund", "Europa", "Gheorgheni", "Grigorescu", "Gruia", "Iris", "Între Lacuri", "Mănăștur", "Mărăști", "Plopilor", "Sopor", "Someșeni", "Zorilor"],
  "Florești": ["Cetatea Fetei", "Donath", "Eroilor", "Florilor", "Mănăstirii", "Muzeul Apei", "Narciselor", "Poligon", "Răzoare", "Șesul de Sus", "Sub Cetate", "Tăuțiului", "Terra", "Vivo"],
  "Baciu": ["Cheile Baciului", "Cornești", "Industrial", "Petrom", "Popești", "Rădaia", "Suceag"],
  "Apahida": ["Câmpenești", "Centru", "Dezmir", "Industrial", "Libertății", "Pata", "Sânnicoară"],
  "Chinteni": ["Centru", "Deușu", "Feiurdeni", "Lac", "Măcicașu", "Pădureni", "Sânmărtin", "Terra Gardens"],
  "Gilău": ["Camping", "Castel", "Centru", "Industrial", "Lac", "Motel", "Șesul de Jos", "Someșu Cald", "Someșu Rece"],
  "Jucu": ["Gadalin", "Jucu de Mijloc", "Jucu de Sus", "Juc-Herghelie", "Tetarom III", "Vișea"],

  // --- CONSTANȚA ---
  "Constanța": ["Abator", "Anadalchioi", "Boreal", "Casa de Cultură", "Centru", "Coiciu", "Dacia", "Faleză Nord", "Gară", "Halta Traian", "Henri Coandă", "Icil", "Inel 1", "Inel 2", "Km 4-5", "Km 5", "Mamaia", "Medeea", "Palas", "Palazu Mare", "Peninsulă", "Poarta 6", "Tomis 1", "Tomis 2", "Tomis 3", "Tomis Nord", "Tomis Plus", "Trocadero", "Viile Noi", "Zona Industrială"],

  // --- COVASNA ---
  "Sfântu Gheorghe": ["Centru", "Ciucului", "Gării", "Lenin", "Simeria", "Stadionului"],

  // --- DÂMBOVIȚA ---
  "Târgoviște": ["CFR", "Centru", "Micro 11", "Micro 12", "Micro 2", "Micro 3", "Micro 4", "Micro 5", "Micro 6", "Micro 8", "Micro 9", "Priseaca", "Suseni"],

  // --- DOLJ ---
  "Craiova": ["1 Mai", "Brazda lui Novac", "Brestei", "Calea Bucureștiului", "Centru", "Cornițoiu", "Craiovița Nouă", "Fața Luncii", "Gara", "George Enescu", "Lăpuș", "Lunca Jiului", "Nisipuri", "Rovine", "Siloz", "Valea Roșie"],

  // --- GALAȚI ---
  "Galați": ["Aurel Vlaicu", "Bădălan", "Barboși", "Centru", "Dimitrie Cantemir", "Dunărea", "Filești", "Gară", "I.C. Frimu", "Mazepa 1", "Mazepa 2", "Micro 13", "Micro 14", "Micro 16", "Micro 17", "Micro 18", "Micro 19", "Micro 20", "Micro 21", "Micro 38", "Micro 39", "Micro 40", "Port", "Siderurgiștilor Vest", "Țiglina 1", "Țiglina 2", "Traian Nord", "Valea Orașului"],

  // --- GIURGIU ---
  "Giurgiu": ["Centru", "Negru Vodă", "Oinac", "Poligon", "Ramadan", "Rudari", "Tineretului"],

  // --- GORJ ---
  "Târgu Jiu": ["1 Mai", "23 August", "9 Mai", "Bârsești", "Calea București", "Centru", "Debarcader", "Drăgoieni", "Gării", "Iezureni", "Meteor", "Preajba", "Slobozia", "Victoriei", "Vădeni"],

  // --- HARGHITA ---
  "Miercurea Ciuc": ["Centru", "Florilor", "Harghita-Băi", "Jigodin-Băi", "Spicului", "Toplița-Ciuc", "Tudor Vladimirescu"],

  // --- HUNEDOARA ---
  "Deva": ["Ceangăi", "Centru", "Dacia", "Dorobanți", "Gojdu", "Micro 15", "Progresul", "Viile Noi", "Zăvoi"],

  // --- IALOMIȚA ---
  "Slobozia": ["Bora", "Centru", "Gării", "Nord", "Slobozia Nouă", "Sud"],

  // --- IAȘI ---
  "Iași": ["Alexandru cel Bun", "Bucium", "Bularga", "Canta", "Cantemir", "Centru", "Copou", "Dacia", "Frumoasa", "Galata", "Gară", "Metalurgie", "Mircea cel Bătrân", "Moara de Vânt", "Nicolina 1", "Nicolina 2", "Păcurari", "Podu de Piatră", "Podu Roș", "Socola", "Tătărași Nord", "Tătărași Sud", "Tudor Vladimirescu", "Țicău"],

  // --- MARAMUREȘ ---
  "Baia Mare": ["Alecsandri", "Centrul Vechi", "Depozitelor", "Ferneziu", "Firiza", "Gării", "Griviței", "Hotvon", "Med3", "Orașul Vechi", "Progresului", "Republicii", "Săsar", "Traian", "Valea Borcutului", "Valea Roșie"],

  // --- MEHEDINȚI ---
  "Drobeta-Turnu Severin": ["Alion", "Banovița", "Centru", "Crihala", "Dudașul Schelei", "Gura Văii", "Kiseleff", "Schela Cladovei", "Splai Mihai Viteazu"],

  // --- MUREȘ ---
  "Târgu Mureș": ["7 Noiembrie", "Ady Endre", "Aleea Carpați", "Budai Nagy Antal", "Centru", "Cornișa", "Dâmbu Pietros", "Gara", "Libertății", "Livezeni", "Mureșeni", "Tudor Vladimirescu", "Unirii"],

  // --- NEAMȚ ---
  "Piatra Neamț": ["Centru", "Ciritei", "Dărmănești", "Doamna", "Gara Veche", "Mărăței", "Precista", "Speranța", "Văleni"],

  // --- OLT ---
  "Slatina": ["Centru", "Clocociov", "Crișan", "Eugen Ionescu", "Gară", "Progresul", "Steaua", "Zahana"],

  // --- PRAHOVA ---
  "Ploiești": ["9 Mai", "Albert", "Bariera București", "Bereasca", "Bulevardul București", "Cameliei", "Centru", "Democrației", "Dorobanțul", "Eroilor", "Găgeni", "Malu Roșu", "Mihai Bravu", "Mimiu", "Nord", "Pictor Rosenthal", "Ploiești Vest", "Republicii", "Sud", "Vest 1", "Vest 2"],

  // --- SATU MARE ---
  "Satu Mare": ["14 Mai", "Carpați 1", "Carpați 2", "Centru Nou", "Centru Vechi", "Horea", "Micro 14", "Micro 15", "Micro 16", "Micro 17", "Sătmărel", "Soarelui", "Solidarității", "Titulescu"],

  // --- SĂLAJ ---
  "Zalău": ["Brădet", "Centru", "Dumbrava", "Dumbrava Nord", "Meseș", "Păcii", "Porolissum", "Simion Bărnuțiu", "Stadion"],

  // --- SIBIU ---
  "Sibiu": ["Broscărie", "Centru", "Cireșica", "Gara", "Gușterița", "Hipodrom 1", "Hipodrom 2", "Hipodrom 3", "Lazaret", "Ștrand", "Terezian", "Tineretului", "Turnișor", "Vasile Aaron", "Valea Aurie"],

  // --- SUCEAVA ---
  "Suceava": ["Areni", "Burdujeni", "Centru", "George Enescu", "Ițcani", "Mărășești", "Obcini", "Zamca"],

  // --- TELEORMAN ---
  "Alexandria": ["1 Mai", "Centru", "Gării", "Peco", "Vedea"],

  // --- TIMIȘ ---
  "Timișoara": ["Aradului", "Blașcovici", "Braytim", "Bucovina", "Calea Girocului", "Calea Lipovei", "Calea Șagului", "Cetate", "Circumvalațiunii", "Dacia", "Elisabetin", "Fabric", "Freidorf", "Fratelia", "Ghiroda", "Iosefin", "Mehala", "Modern", "Odobescu", "Plopi", "Ronat", "Soarelui", "Steaua", "Tipografilor", "Torontalului"],

  // --- TULCEA ---
  "Tulcea": ["23 August", "C5", "Centru", "E3", "Neptun", "Vest"],

  // --- VASLUI ---
  "Vaslui": ["13 Decembrie", "Ana Ipătescu", "Brodoc", "Centru", "Gară", "Gura Bustei", "Moara Grecilor", "Rediu", "Traian", "Viișoara"],

  // --- VÂLCEA ---
  "Râmnicu Vâlcea": ["1 Mai", "Căzănești", "Centru", "Copăcelu", "Goranu", "Lenin Sud (Petrișor)", "Nord", "Ostroveni", "Râureni", "Stolniceni", "Traian", "Troianu"],

  // --- VRANCEA ---
  "Focșani": ["Bahne", "Centru", "Gară", "Laminorul", "Mândrești", "Obor", "Sud"]
};